# -*- coding: utf-8 -*-
"""kokoro_pauses_colab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EP13WTNFP_UsyqKVnOI-3pgkBiV0vJDj

# Kokoro TTS — 50 ms pauses after chosen words, with word timestamps

Generates audio from the iOS 27 article via the RunPod Kokoro v2 endpoint, inserts **50 ms of silence after specified word indices**, and returns word timestamps that already account for the inserted pauses.

Run the cells top to bottom. You will be prompted for `RUNPOD_API_KEY` and `KOKORO_ENDPOINT_ID`.

Two guards are baked in: `iOS 27` is expanded to `iOS twenty-seven` so the forced aligner (a–z only) does not drop the digit token and shift later indices, and any out-of-range index is reported and skipped.
"""

# requests ships with Colab; this is just a safeguard.
!pip -q install requests >/dev/null

import os, getpass

RUNPOD_API_KEY = os.environ.get('RUNPOD_API_KEY') or getpass.getpass('RUNPOD_API_KEY: ')
KOKORO_ENDPOINT_ID = os.environ.get('KOKORO_ENDPOINT_ID') or getpass.getpass('KOKORO_ENDPOINT_ID: ')

# Colab alternative (Secrets panel, key icon on the left):
#   from google.colab import userdata
#   RUNPOD_API_KEY = userdata.get('RUNPOD_API_KEY')
#   KOKORO_ENDPOINT_ID = userdata.get('KOKORO_ENDPOINT_ID')

TEXT = """Siri's AI overhaul may have been the headline announcement at Apple's Worldwide Developers Conference earlier this month, but Apple's broader AI strategy is taking shape through a series of smaller features embedded across its software.
Rather than asking consumers to adopt the new AI-powered version of Siri to get all the benefits that AI brings, the company is weaving AI into the apps and services people already use, with a focus on solving real-world problems. The result is that your iPhone will be able to split restaurant bills among friends, secure your passwords after data breaches, automate tasks, and organize information with less manual effort, among other things.
Individually, these features may not be as dramatic as a Siri that finally understands your personal context and can take action on your behalf. But combined, they showcase a vision for AI that's less about chatting with a bot and more about making Apple's software itself feel smarter and more capable.
Beyond Siri AI, here are the smaller AI features in iOS 27 that we're most looking forward to using. The features are live now in the developer beta and will soon arrive in the public beta, before iOS 27's general public release later this fall."""

# Pause is inserted AFTER each of these word indices (0-based, in the aligned word list).
PAUSE_AFTER = [2, 8, 13, 16, 21, 30, 34, 46, 54, 62, 67, 74, 87, 95, 100, 107,
               115, 124, 131, 139, 146, 153, 158, 167, 177, 186, 194, 203]

PAUSE_MS     = 50           # silence to insert after each chosen word
VOICE        = 'af_heart'   # see README language/voice table
LANG_CODE    = 'a'          # 'a' = American English
SPEED        = 1.0
CROSSFADE_MS = 5.0          # click-free blend; keep < PAUSE_MS
PROBE        = True         # verify index->word against the model's real output before generating
OUT_WAV      = 'ios27_pauses.wav'

# Numbers must be letters or MMS_FA drops the token and shifts every later index.
# \\b27\\b matches '27' and the 27 inside \"27's\", apostrophe style irrelevant.
NUMBER_FIXES = {r'\b27\b': 'twenty-seven'}

import re, io, base64, unicodedata, requests

def clean_word(w):
    """Mirror of the server's _clean_word (Latin branch): strip punctuation, fold accents."""
    c = re.sub(r'[^\w\s]', '', w, flags=re.UNICODE).strip()
    if not c:
        return ''
    n = unicodedata.normalize('NFD', c)
    return ''.join(ch for ch in n if unicodedata.category(ch) != 'Mn')

def normalize_numbers(text, fixes):
    for pat, repl in fixes.items():
        text = re.sub(pat, repl, text)
    return text

def pre_align_wordlist(text):
    """The word order/index space pause_after uses, assuming every word aligns."""
    return [w for w in text.split() if clean_word(w)]

def runpod_runsync(payload, timeout=600):
    url = f'https://api.runpod.ai/v2/{KOKORO_ENDPOINT_ID}/runsync'
    headers = {'Authorization': f'Bearer {RUNPOD_API_KEY}', 'Content-Type': 'application/json'}
    r = requests.post(url, json={'input': payload}, headers=headers, timeout=timeout)
    r.raise_for_status()
    body = r.json()
    out = body.get('output', body)
    if isinstance(out, dict) and out.get('error'):
        raise RuntimeError(out['error'])
    return out

# Normalize, then sanity-check the requested indices.
TEXT_N = normalize_numbers(TEXT, NUMBER_FIXES)
local_words = pre_align_wordlist(TEXT_N)
print(f'local word count: {len(local_words)}  (valid indices 0..{len(local_words)-2})')

valid   = [i for i in PAUSE_AFTER if 0 <= i < len(local_words) - 1]
dropped = [i for i in PAUSE_AFTER if i not in valid]
if dropped:
    print('out of range, will be ignored:', dropped)

ref = local_words
if PROBE:
    probe = runpod_runsync({'text': TEXT_N, 'voice': VOICE, 'lang_code': LANG_CODE,
                            'speed': SPEED, 'timestamps': True})
    server_words = [wt['word'] for wt in probe.get('word_timestamps', [])]
    print(f'server aligned word count: {len(server_words)}')
    if len(server_words) != len(local_words):
        print('WARNING: counts differ -> the aligner dropped/added tokens; '
              'indices below come from the SERVER list and are authoritative.')
    ref = server_words
    valid = [i for i in PAUSE_AFTER if 0 <= i < len(ref) - 1]

print('\nindex -> word the 50 ms lands AFTER:')
for i in valid:
    print(f'  {i:>3}: {ref[i]!r}')

# Generate: synth + 50 ms pauses + offset-corrected timestamps.
out = runpod_runsync({
    'text': TEXT_N, 'voice': VOICE, 'lang_code': LANG_CODE, 'speed': SPEED,
    'timestamps': True, 'word_boundaries': True,
    'pause_after': valid, 'micro_pause_ms': PAUSE_MS, 'crossfade_ms': CROSSFADE_MS,
})

audio = base64.b64decode(out['audio_base64'])
with open(OUT_WAV, 'wb') as f:
    f.write(audio)

print(f"duration: {out['duration_seconds']}s   sample_rate: {out['sample_rate']}   "
      f"pauses inserted: {len(valid)}")

import IPython.display as ipd
ipd.display(ipd.Audio(audio, rate=out['sample_rate']))

# Word timestamps (already shifted for the inserted pauses).
ts = out.get('word_timestamps', [])
print(f'{len(ts)} words\n')
for k, wt in enumerate(ts):
    gap = ''
    if k + 1 < len(ts):
        g = (ts[k+1]['start'] - wt['end']) * 1000
        gap = f'  gap->next {g:5.0f} ms'
    print(f"{k:>3}  {wt['word']:<16} {wt['start']:>7.3f} - {wt['end']:>7.3f}{gap}")

# Download the WAV.
from google.colab import files
files.download(OUT_WAV)

# Add 1 second of silence after selected words in OUT_WAV.
# Assumes OUT_WAV is a path string, for example:
# OUT_WAV = "/content/audio.wav"
# If OUT_WAV is not defined, the cell will ask you to upload a WAV file.

import os
import numpy as np
from scipy.io import wavfile

# ---------- Input handling ----------
try:
    input_path = OUT_WAV
except NameError:
    from google.colab import files
    uploaded = files.upload()
    if not uploaded:
        raise ValueError("No WAV file uploaded.")
    input_path = next(iter(uploaded.keys()))

if not isinstance(input_path, str):
    input_path = str(input_path)

if not os.path.exists(input_path):
    raise FileNotFoundError(f"Audio file not found: {input_path}")

# ---------- Pause targets ----------
# Format: word_index: (word, word_end_time_seconds)
PAUSE_AFTER_WORDS = {
    2: ("overhaul", 1.480),
    8: ("announcement", 3.131),
    13: ("Conference", 5.381),
    16: ("month,", 6.292),
    21: ("strategy", 8.622),
    30: ("features", 11.873),
    34: ("software.", 13.724),
    46: ("Siri", 18.575),
    54: ("brings,", 21.266),
    62: ("apps", 24.077),
    67: ("use,", 26.007),
    74: ("problems.", 29.158),
    87: ("bills", 32.689),
    95: ("breaches,", 36.200),
    100: ("information", 39.351),
    107: ("things.", 42.062),
    115: ("dramatic", 45.733),
    124: ("context", 49.023),
    131: ("behalf.", 50.954),
    139: ("AI", 54.105),
    146: ("bot", 55.795),
    153: ("itself", 58.686),
    158: ("capable.", 60.356),
    167: ("features", 64.748),
    177: ("using.", 68.359),
    186: ("beta", 71.350),
    194: ("beta,", 73.780),
}

PAUSE_SECONDS = 1.0

# ---------- Read audio ----------
sr, audio = wavfile.read(input_path)

if audio.ndim == 1:
    silence = np.zeros(int(sr * PAUSE_SECONDS), dtype=audio.dtype)
else:
    silence = np.zeros((int(sr * PAUSE_SECONDS), audio.shape[1]), dtype=audio.dtype)

# ---------- Insert silences ----------
insert_times = sorted(t for _, t in PAUSE_AFTER_WORDS.values())

pieces = []
cursor = 0
audio_len = len(audio)

for t in insert_times:
    insert_sample = int(round(t * sr))
    insert_sample = max(0, min(insert_sample, audio_len))

    pieces.append(audio[cursor:insert_sample])
    pieces.append(silence)

    cursor = insert_sample

pieces.append(audio[cursor:])

output_audio = np.concatenate(pieces, axis=0)

# ---------- Write output ----------
base, ext = os.path.splitext(input_path)
output_path = f"{base}_with_1s_pauses.wav"

wavfile.write(output_path, sr, output_audio)

print(f"Done.")
print(f"Input:  {input_path}")
print(f"Output: {output_path}")
print(f"Inserted pauses: {len(insert_times)}")
print(f"Added duration: {len(insert_times) * PAUSE_SECONDS:.1f} seconds")
print(f"Original duration: {audio_len / sr:.3f} seconds")
print(f"New duration: {len(output_audio) / sr:.3f} seconds")

# Optional Colab download
try:
    from google.colab import files
    files.download(output_path)
except Exception:
    pass

